### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by alexisvincent** [jdnavarro/graphql-haskell#10]
What is the status on this project?

**Comment by jdnavarro** [comment]
Sorry if the project looks abandoned. I'm these days in the process of relocating and starting a new job, so things are pretty hectic from my end.

However, before officially starting my new job on June 15th, I'd like to release the new features in `master`, mainly the executor and the schema DSL. The basic functionality is done, I just have to complete the handling of fragments and directives if I remember correctly.

PR are welcome, too!

**Comment by alexisvincent** [comment]
Completely understand. I was just curious :)
