### ISSUE TITLE
Offer

### ISSUE THREAD

**Issue by jasonzoladz** [jdnavarro/graphql-haskell#17]
I'd pay $500 for you to get this into production shape -- complete the stuff that you mentioned in #12, the `TODO`, add introspection, and release to Stackage.  (Heck, I'd pay $300 without introspection.)

Let me know if you might have time.

**Comment by jdnavarro** [comment]
Thanks for the bounty offer but, although my intention is to get back on my spare time to this project, my hands are full on my daytime job at the moment.
