### ISSUE TITLE
Update Hackage package info on exposed modules

### ISSUE THREAD

**Issue by marcotoniut** [jdnavarro/graphql-haskell#21]
I'm kinda new to the haskell scene. But if I understood this correctly, the package information on Hackage is only exposing a crippling amount of modules to use the library properly. Or is this common for newly developed libraries?

**Comment by jdnavarro** [comment]
In the latest version I believe there wasn't any module related to execution or schema definition, so you could only use the parser and the printer.

There is a rough implementation of the execution and schema definitions in development, but I won't make the release until at least a bare minimum for such functionality works properly. For the latest development you can have a look at the `core` branch which I'm about to merge soon into `master`. It includes support for interpreting fragments and variables.

Unfortunately, I have very little time for this project, so I can't recommend this library for any real work, but PRs are always welcomed.
